### ISSUE TITLE
catkin build terrain_server have error?

### ISSUE THREAD

**Issue by ghost** [robot-locomotion/dwl-distro#4]
when i  catkin build terrain_server 
Unsuccessful！show:

Errors     << terrain_server:make /home/n/mynav_ws/logs/terrain_server/build.make.002.log
/usr/local/lib/libdwl.so: undefined reference to `dwl::model::FloatingBaseSystem::getSystemCoM(Eigen::Matrix<double, 6, 1, 0, 6, 1> const&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&)'
/usr/local/lib/libdwl.so: undefined reference to `dwl::model::FloatingBaseSystem::getSystemCoMRate(Eigen::Matrix<double, 6, 1, 0, 6, 1> const&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&, Eigen::Matrix<double, 6, 1, 0, 6, 1> const&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/n/mynav_ws/devel/.private/terrain_server/lib/terrain_server/obstacle_map_server] Error 1
make[1]: *** [CMakeFiles/obstacle_map_server.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/local/lib/libdwl.so: undefined reference to `dwl::model::FloatingBaseSystem::getSystemCoM(Eigen::Matrix<double, 6, 1, 0, 6, 1> const&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&)'
/usr/local/lib/libdwl.so: undefined reference to `dwl::model::FloatingBaseSystem::getSystemCoMRate(Eigen::Matrix<double, 6, 1, 0, 6, 1> const&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&, Eigen::Matrix<double, 6, 1, 0, 6, 1> const&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/n/mynav_ws/devel/.private/terrain_server/lib/terrain_server/terrain_map_server] Error 1
make[1]: *** [CMakeFiles/terrain_map_server.dir/all] Error 2
make: *** [all] Error 2

how can i solve it?

**Comment by cmastalli** [comment]
If you use the dwl-distro (master branch) all packages should be compatible with dwl. However I see that you installed dwl inside /usr/local. Please remove it, and compile everything (including dwl) using catkin.

Let me know if this fixes your problem!

**Comment by ghost** [comment]
After i remove dwl inside /usr/local,catkin
show:

Errors     << dwl_msgs:cmake /home/n/mynav_ws/logs/dwl_msgs/build.cmake.002.log
Dynamic Whole-Body Locomotion (DWL) ROS messages
Copyright (C) 2014-2018 Carlos Mastalli, <carlos.mastalli@@laas.fr>
All rights reserved.
Released under the BSD 3-Clause License.
CMake Error at /home/n/mynav_ws/devel/share/dwl/cmake/dwlConfig.cmake:148 (message):
  Project 'dwl_msgs' tried to find library 'dwl'.  The library is neither a
  target nor built/installed properly.  Did you compile project 'dwl'? Did
  you find_package() it before the subdirectory containing its code is
  included?
Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  CMakeLists.txt:11 (find_package)

how can i solve it?
i already catkin build dwl and success in my wordspace

**Comment by ghost** [comment]
i solve it !should compile with catkin_make ,catkin build is not work!why?
after  compile succesful ! then how i run the demo?

**Comment by cmastalli** [comment]
Thanks for reporting it. I will close this issue. Feel free to open other if it's needed.

**Comment by cmastalli** [comment]
Thanks for reporting it. I will close this issue. Feel free to open other if it's needed.
