### ISSUE TITLE
after compile succesful ! then how i run the demo?

### ISSUE THREAD

**Issue by ghost** [robot-locomotion/dwl-distro#5]
after compile succesful ! then how i run the demo?
how could i use this control hyq?

**Comment by cmastalli** [comment]
What exactly are you interested to? There are few core functions. For instance you can have a look inside dwl/sample. There you can find basic examples of c++ functions and its python bindings. You can compile and run them by manually building dwl and setting up the cmake flag for sample code.

Please be aware that Python bindings aren't compatible yet with the latest versions of the urdf (i.e. latest than ROS indigo). Additionally they aren't generated by default, you need to active it through cmake flag

**Comment by ghost** [comment]
i want to run this with hyq simulation in gazebo,want to control hyq robot run

**Comment by cmastalli** [comment]
You need to clone and compile hyq-description (https://github.com/iit-DLSLab/hyq-description). We use an custom version of ros-control and its interface. At the time being this version isn't open source. You can turn it off by commenting this line: https://github.com/iit-DLSLab/hyq-description/blob/master/gazebo/gazebo.urdf.xacro#L8.

Please note that dwl-distro packages provide you an easy way to design your motion controller and planner. We havem't opened the source code of our motion controllers and planners. As starting point, I suggest you to run a standard PD controller from ros-control.

**Comment by ghost** [comment]
i already compile hyq-description,your mean is dls_gazebo_interface/DLSHWSim isn't open?
how i use dwl-distro packages write my controller? Please give me some advice. Thank you very much.@cmastalli

**Comment by cmastalli** [comment]
Yes, it's not open. This is the custom Gazebo/ros-control interface to our controllers The controller code isn't open source neither. You can visit the ros-control tutorials to learn how to implement a controller.

With dwl you can compute kinematics and dynamics quantities (i.e. Jacobians, inverse dynamics, etc). You might want to see the examples inside dwl/sample or have a look of the whole-body state publisher (wb_state_publisher). Note that the wb_state_publisher publishes from ros-control some information computed by dwl.

**Comment by cmastalli** [comment]
I will close this issue. If it's needed, feel free to re-open it.
